# Generated by Django 4.2.3 on 2023-07-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketmaster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.IntegerField(null=True),
        ),
    ]
