# Generated by Django 4.2.3 on 2023-07-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketmaster", "0002_event_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="img_url",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="venue_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
