# Generated by Django 4.2.3 on 2023-07-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketmaster", "0004_event_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_description",
            field=models.TextField(max_length=300, null=True),
        ),
    ]
